services:
  # 1. Container chạy code Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hrm_app
    volumes:
      - .:/var/www
    networks:
      - hrm_network

  # 2. Container MySQL (Giữ nguyên cấu hình cũ của bạn)
  mysql_db:
    image: mysql:8.0
    container_name: hrm_database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hrm_demo
      MYSQL_ROOT_PASSWORD: root_secret
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - hrm_network

  # 3. Container Nginx (Làm nhiệm vụ tiếp nhận yêu cầu từ trình duyệt)
  nginx:
    image: nginx:alpine
    container_name: hrm_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - hrm_network
  frontend:
    build:
      context: ../frontend-hr-HaiXom # Chỉ đường sang thư mục Frontend
      dockerfile: Dockerfile
    container_name: hrm_frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend-hr-HaiXom:/app
      - /app/node_modules # Giữ node_modules độc lập bên trong Docker
    environment:
      - CHOKIDAR_USEPOLLING=true # Giúp Vite nhận diện thay đổi file trên Windows
    networks:
      - hrm_network

networks:
  hrm_network:
    driver: bridge